### PR TITLE
#1 Topic: Frameworks

### PR DESCRIPTION
**Pull request by mohit-rathee**
I describes about frameworks and how they are useful in creating software.
And also having an understanding about web-development  I elaborated about web-frameworks and how they generally works.

### CODE REVIEW

**Comment by dikshant182004** [comment]
well done

**Comment by dikshant182004** [comment]
hii @mohit-rathee .I have gone through your github profile .it was good .I just want to ask that there is a project that u have made "web chat".was it made by you.

**Comment by mohit-rathee** [comment]
Yes, I started it as my first project to create a real-world application, but as complexity increased, I began putting more effort into it.
As time has passed, I've developed a hobby for maintaining this project.

**Comment by dikshant182004** [comment]
It means that all the code that is there in it is written by u and u know all of them that why u have written that.

**Comment by mohit-rathee** [comment]
Yes every single line of code is wriiten by me

**Comment by dikshant182004** [comment]
first year mein ho

**Comment by mohit-rathee** [comment]
I took a long time to reach here. Maybe because by the time I learn about new technologies I merged them in my project.
Like when the time I heard about websockets and indexedDB.

**Comment by dikshant182004** [comment]
nice work man .keep it up .plz tell me your year and class.

**Comment by mohit-rathee** [comment]
Thanks,
I am in (UIET) 1st year CSE-A.
Roll no 68.

**Comment by dikshant182004** [comment]
okay well done . Today ,I got inspired from u man.open source start kardo hacktoberfest chal raha hain

**Comment by dikshant182004** [comment]
aur gsoc bhi aane wala hain

**Comment by mohit-rathee** [comment]
Haan main bhi interesting projects dhund rha hu.

**Pull request merged**
